dubbo:
  application:
    name: ymall-web
  registry:
    address: 192.168.157.128:2181
    protocol: zookeeper
  consumer:
    check: false
    timeout: 3000
server:
  port: 8080
ymall:
  jwt:
    tokenHeader: Authorization
    secret: ywc_2020
    expiration: 604800
    tokenHead: Token
aliyum:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: 
    accessKeySecret: 
    bucketName: 
    policy:
      expire: 300
    maxSize: 10
    dir:
      prefix: ymall/images/
