dubbo:
  application:
    name: ymall-pms
  registry:
    address: 192.168.157.128:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 21080
  consumer:
    check: false
  scan:
    base-packages: com.ywc.ymall.pms.service.impl
spring:
  redis:
    host: 192.168.157.128
    port: 6379
  elasticsearch:
    jest:
      uris[0]: http://192.168.157.128:9200

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
