dubbo:
  application:
    name: ymall-ums
  registry:
    address: 192.168.157.128:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 21280
  consumer:
    check: false
  scan:
    base-packages: com.ywc.ymall.ums.service.impl

