dubbo:
  application:
    name: ymall-pms
  registry:
    address: 192.168.157.128:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
  consumer:
    check: false
  scan:
    base-packages: com.ywc.ymall.pms.service.impl
