dubbo:
  application:
    name: ymall-sms
  registry:
    address: 192.168.157.128:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 21180
  consumer:
    check: false
  scan:
    base-packages: com.ywc.ymall.sms.service.impl